### PR TITLE
T-107/ flyway_fixes

### PR DESCRIPTION
**Pull request by fiorellamansilla**
- Refactored Flyway setup in order to get the Gradle commands to work properly and to enable the FlywayClean task
- Updated versions of some dependecies because of vulnerabilities
- Eliminated old Flyway scripts from db.migration

### CODE REVIEW

**Review by diego-mansilla — COMMENTED** [review]
Why deleting all files

**Comment by fiorellamansilla** [comment]
I made a lot of changes to the previous table scripts that resulted in several checksum mismatches. Because of the Flyway configuration on build.gradle, I could not use the Gradle commands properly at that time, so I could not run the FlywayRepair task. All this made me realize that it was a better alternative to fix the configuration, run the FlywayClean task and have a clean start with the final updated scripts.

**Review by diego-mansilla — APPROVED** [review]
This works now, but if you are working with several engineers, this would break all their local dev environemnts

**Comment by fiorellamansilla** [comment]
Understood!

**Pull request merged**
